---
- hosts: all
  become: yes
  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /var/www
    app_root: html_demo_site-main
  tasks:
    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
    - name: Copy website files to the server's document root
      copy:
        src: /tmp/ansibletemplatetesting/index.html
        dest: /var/www/html/index.nginx-debian.html
        mode: preserve
    - name: Run Apt Update
        shell: apt update && apt install -y python-apt    
        owner: root
        group: root
        mode: 0644
   - name: Copy the style files to destination folder.
        copy: >
        src: /tmp/ansibletemplatetesting/style.css
        dest: /var/www/html/style.css
        owner: root
        group: root
        mode: 0644
    - name: Copy the javascript files to destination folder.
        copy: >
        src: /tmp/ansibletemplatetesting/index.js
        dest: /var/www/html/index.js
        owner: root
        group: root
        mode: 0644
    - name: restart nginx
        command: service nginx restart    
