#!/bin/bash
apt update
apt install software-properties-common -y
apt-add-repository --yes --update ppa:ansible/ansible
apt update
apt install ansible -y
apt install nginx -y
apt install python-apt -y
apt install git -y
apt install stress -y
git clone https://github.com/friends4433/jsclock.git /myrepo
######USE aws-autoscaling branch for testing aws autoscaling##########################
######GIVE ONLY ABOVE IN THE USER DATA FOR AMI IMAGE FOR AWS AUTOSCALING##########
#
#####GIVE BELOW IN THE LAUNCH CONFIG USERDATA#####################################
ansible-playbook /myrepo/playbook.yaml

======================OR-OR-OR-OR=============================================

cp /myrepo/index.html /var/www/html/index.nginx-debian.html
cp /myrepo/style.css /var/www/html/style.css
cp /myrepo/script.js /var/www/html/script.js
cp /myrepo/imgs /var/www/html/imgs
